### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by lukicsasa** [UrosNikolic/seneca-microservice-boilerplate#1]
Hello, awesome job creating this microservice boiler plate.
Can you please add semicolons (;) at the end of declarations. It hurts my eyes so bad...

Regards

**Comment by UrosNikolic** [comment]
@lukicsasa In respect to your comment, as with all coding style arguments this will be a never-ending debate with no reasonable conclusion. This is a boilerplate to use as a guide for building microservices as such, it is completely up to you to use or not to use semicolons, consistency is important. Whatever you decision is just make sure you are familiar with automatic semicolon insertion (ASI).
